### ISSUE TITLE
hiden "Aucun nouveau message"

### ISSUE THREAD

**Issue by SOF40** [Wiripse/HFRGMTools#11]
thanks :o

**Comment by Wiripse** [comment]
Se baser sur "sujets compacts" : quand une catégorie n'a aucun post visible, elle dégage complètement.

Ajouter une option en ce sens : soit on dégage les cat vides, soit on la laisse et on ajoute le txt "Aucun nouveau message"

**Comment by SOF40** [comment]
[:sof40:9]

**Comment by Wiripse** [comment]
Fait !

**Comment by SOF40** [comment]
[:sof40:9]
