### ISSUE TITLE
Pas de colorisation de l’enveloppe quand on a un nouveau MP

### ISSUE THREAD

**Issue by ezzz** [Wiripse/HFRGMTools#13]
Safari Catalina + ViolentMonkey

Qu’on ait des MPs non lus ou pas c’est la même chose, la couleurs de l’enveloppe ne change pas.

**Comment by Wiripse** [comment]
Tu es bien sur une page de drapeaux ? Genre [cyans](https://forum.hardware.fr/forum1f.php?config=hfr.inc&owntopic=1&new=0&nojs=0) ?

**Comment by Wiripse** [comment]
Sur la [home](https://forum.hardware.fr/) ça ajoute l'onglet MP "simple". Il ne détecte pas qu'il y a du non lu car sur cette page l'info non lus n'est pas dispo dans le header mais en tant que nouvelle catégorie. 

Est-ce bien ce problème ?

**Comment by ezzz** [comment]
Nope mais c'est une bonne question
J'ai le pb avec la page Vos Sujets :
https://forum.hardware.fr/forum1f.php?config=hfr.inc&owntopic=1&new=0&nojs=0
Et aussi quand je rentre dans une cat, genre discussion :
https://forum.hardware.fr/forum1.php?config=hfr.inc&cat=13&page=1&subcat=&sondage=0&owntopic=1&trash=0&trash_post=0&moderation=0&new=0&nojs=0&subcatgroup=0

Mais j'ai une piste, avec un multi j'ai pas le pb 
J'ai le pb qu'avec ezzz au final
Sans doute un pb de personnalisation du forum avec ezzz? Ou alors j'ai fait un tunning de HFR4K avec ezzz que je n'ai pas sur les autres pseudos?

**Comment by ezzz** [comment]
J'ai regardé ton script :o

Je pense avoir compris pourquoi ca marche pas

Avec ezzz, mon icône de MP est la suivante:
https://forum-images.hardware.fr/themes_static/images/defaut/newmp.gif

Avec un multi ou ça fonctionne j'ai ça:
https://forum-images.hardware.fr/themes_static/images_forum/1/newmp.gif

Les deux pointent bien vers l'icône de nouveau MP du forum. Je ne sais pas d'où vient cette différence par contre...

**Comment by ezzz** [comment]
ha ben c'est le jeu d'icônes du forum
J'avais "Défaut", en mettant "Selon le forum consulté" (WTF ????) ça fonctionne

**Comment by Wiripse** [comment]
Verdict : bug ou PEBCAK ? :)

**Comment by ezzz** [comment]
Bug :o
Avoir le set d’icône a Defaut y a rien de farfelu là dedans 
Et ça évitera que le prochain ait le même pb

**Comment by Wiripse** [comment]
Oké !

**Comment by Wiripse** [comment]
J'ai profité de la 2020.01.11.1 pour modifier la façon dont est gérée l'icône

Tu peux me dire si ça résout ton problème ?

Mercé

**Comment by ezzz** [comment]
Ça marche chef ! Je teste ça

**Comment by Wiripse** [comment]
Il a validé en MP 😉

**Comment by ezzz** [comment]
Oui pardon d’être sorti du proccess git 😔
