### ISSUE TITLE
Compatibilité de HFR4K avec [HFR] New Page Number

### ISSUE THREAD

**Issue by roger21** [Wiripse/HFRGMTools#16]
Compatibilité de HFR4K avec [HFR] New Page Number sur la fonctionnalité ezzzi drap notamment,

[HFR] New Page Number modifie le lien des drapals pour gérer l'ouverture en masse sur les drapals

pour prendre en compte cette modification (et afin de pouvoir récupérer l'adresse du drapal) il faut remplacer le code

`topic.querySelector('a').href`

à la ligne 1157 par

`topic.querySelector('a').hasAttribute("href") ? topic.querySelector('a').href : topic.querySelector('a').dataset.href`

et

`caseDrapal.querySelector('a').href;`

à la ligne 1497 par

`caseDrapal.querySelector('a').hasAttribute("href") ? caseDrapal.querySelector('a').href : caseDrapal.querySelector('a').dataset.href`

ou quelque chose de similaire qui récupère le dataset.href quand le href n'est pas présent

**Comment by Wiripse** [comment]
Done a1f28b670d90c7b19b055467cf8425fa66326060

**Comment by roger21** [comment]
:jap:
