### ISSUE TITLE
[MPStorage] problème de création du mp, le pseudal est encodé 2 fois (et deux autres problèmes)

### ISSUE THREAD

**Issue by roger21** [Wiripse/HFRGMTools#17]
Dans mp storage le pseudal est récupéré depuis le cookie à la ligne 287

mais le contenue du cookie est déjà encodé (on dirait un urlencode de php, dans mon cas, un pseudal avec espace, l'espace est remplacé par un +, il faudrait tester avec un pseudal avec des caractères speciaux)

il est ensuite ré-encodé avec encodeURIComponent lors de la requête à la ligne 269 du coup les caractères déjà encodés sont alors sur-encodés et le pseudal n'est pas reconnu par le forum, la création du mp échoue (pseudal inconnu)

il faut voir si on peut se passer du encodeURIComponent, dans mon cas ça marche mais il faudrait vérifier avec des caractères spéciaux

Deux autre problèmes :

- lorsque ce processus de création plante il n'y a pas de garde-fou

le script part en boucle sur des requêtes ajax sans fin (findStorageMPOnPage puis createStorageMP (qui échoue) puis à nouveau findStorageMPOnPage et rebelote), il faut donc gérer les cas de plantage pour stopper le script, soit en analysant la réponse du forum sur la création du mp et s'arrêter si la réponse n'est pas bonne (le forum renvoie une page basique avec un truc du genre "message posté" puis redirige sur la page des mp) soit simplement en stoppant le script si il passe une deuxième fois dans createStorageMP

et de plus il faudrait rajouter par sécurité des timeout sur les requêtes ajax

par exemple remplacer la ligne 186 par :

`window.setTimeout(function() {mpStorage.findStorageMPOnPage(pageId + 1, callback);}, 250);`

la ligne 193 par :

`window.setTimeout(function() {mpStorage.findStorageMPOnPage(1, callback);}, 250);`

et faire de même sur la création du mp, soit sur le bloc à la ligne 189 soit à la ligne 274

ou mieux, gérer un tempo globale sur les appel à loadPage

- le code de récupération des pages est monstrueusement obsolète et n'a aucun sens aujourd'hui

il faut virer getElementByXpath et utiliser des querySelector(All)

et virer complètement la toyoajaxlib (et son horreur window.ActiveXObject) et la remplacer par des requêtes fetch en same-origin qui forcent le script a n’accéder qu'à hfr et rien d'autre

**Comment by roger21** [comment]
? tu t'es planté

**Comment by Wiripse** [comment]
Je me suis planté dans le commentaire de commit et Github a fermé l'issue tout seul :o

**Comment by roger21** [comment]
ah oui en effet

**Comment by roger21** [comment]
concernant la récupération du pseudal via le cookie, ce dernier est déjà encodé (le cookie est encodé)

il faut le désencoder dans getUsername ou dans getCookie avec un decodeURIComponent avant de le stocker

et continuer à l’encoder chaque fois qu'il est utilisé dans les requêtes (comme actuellement)

**Comment by Wiripse** [comment]
Fixed :

- Gestion pseudos chelous

- Suppression xpath

- Suppression toyoajaxlib

Via https://github.com/Wiripse/HFRGMTools/commit/a6446fdf72d34581ceecc52d4d3f404e183b60ba
