### ISSUE TITLE
[MPStorage] informer l'utilisateur et possibilité de choisir un multi

### ISSUE THREAD

**Issue by roger21** [Wiripse/HFRGMTools#23]
à l'initialisation du mp, l'utilisateur doit pouvoir choisir un multi perso plutôt que d'utiliser MPUser, s'il n'en choisit pas MPuser est utilisé et l'utilisateur doit être informé sur qui gère MPUser

**Comment by Wiripse** [comment]
Je n'ai pas compris
Actuellement tout est automatique pour ne pas demander une intervention de l'user 

On se base sur les infos en localStorage. Si ça ne marche pas (l'user a changé de compte), on ré-initialise les infos. 
MPStorage étant une librairie, on ne peut pas se permettre de demander une saisie user car on ne sait pas comment elle sera utilisée.
Et demander une saisie user ne semble pas utile car on peut tout faire automatiquement en prenant l'user en cookie

**Comment by roger21** [comment]
le problème c'est que mpstorage fournit des informations personnelles à un utilisateur tiers sans le consentement ni la connaissance explicite de l'utilisateur

peu importe que ce soit fait via le script ou la bibliothèque, je ne sais pas qui d'autre utilise mpstorage directement, mais je ne vois pas de problème a balancer un window.confirm pour saisir un multi (pour choisir explicitement à qui est adressé le mp) ou un window.alert pour expliquer qui est mpuser durant la phase d'initialisation (évidement que si le mp n'est pas déjà créé ou trouvé)

**Comment by roger21** [comment]
quand le mp est trouvé la bibliothèque reste parfaitement silencieuse sur les opérations mais lors de la création du mp, l'utilisateur doit être informé de ce qui se passe, pouvoir refuser ou choisir un multi à lui

**Comment by roger21** [comment]
pardon multimp pas mpuser

**Comment by Wiripse** [comment]
Tu parles de la variable _mpRecipient_ qui est valorisée par défaut à **MultiMP** ?
https://github.com/Wiripse/HFRGMTools/blob/master/MPStorage.user.js#L13

**MultiMP** est un compte créé par Marc à ma demande, uniquement dans le but d'être destinataire des MPStorage. Marc a autant accès à ce compte qu'à la BDD directement, j'y vois donc difficilement un problème de confidentialité. 

Ici l'utilisateur tiers c'est _HFR_; si l'user du script ne fait pas confiance à _HFR_, il n'utilise pas _HFR_ et n'a aucune raison d'utiliser le script...

Je veux bien ajouter cette information dans le guide utilisateur, mais faire une alerte et demander l'avis de l'utilisateur c'est rendre les choses bien trop compliquées pour un but dont je ne vois pas le sens.

**Comment by roger21** [comment]
je voulais dire window.proimpt et window.confirm

mais c'est exactement ça :
`MultiMP est un compte créé par Marc à ma demande, uniquement dans le but d'être destinataire des MPStorage. Marc a autant accès à ce compte qu'à la BDD directement, j'y vois donc difficilement un problème de confidentialité.`

je dis pas que y'a un problème de confidentialité, je dis que l'utilisateur doit être informé de ce qu'est muultimp

par défaut tout ce qu'il voit c'est qu'il envoie des données personnelles à un utilisateur tiers qu'il ne connais pas

et donc rajouter ce message explicatif, lui demander son accord et lui proposer d'utiliser un multi perso s'il le souhaite (puisque c'est techniquement faisable et facile).

encore une fois je ne vois pas le problème de le faire dans la bibliothèque, elle n'est pas utilisé par autre chose qui n'aie access a une page web et qui ne puisse intéragire avec l'utilisateur (avec des minimalistes window.proimpt et window.confirm)

si ça doit être fait au niveau du script c'est pas fiable

juste une succession de window.confirm et de window.prompt dans la phase de crétaion du mp et stockage du multi dans un gm.setvalue("mp_storage_multi", balabla);

**Comment by Wiripse** [comment]
J'ai ajouté ceci à la doc : https://wiripse.github.io/HFRGMTools/#avertissement-vie-priv%C3%A9e

Sincèrement ce que tu demandes me semble overkill et contraignant pour l'utilisateur final. 

Et si je travaille là-dessus ça veut dire que je ne fais pas avancer HFR4K, ce qui est problématique à mes yeux vu le peu de temps que j'ai à y consacrer...

**Comment by roger21** [comment]
> J'ai ajouté ceci à la doc : https://wiripse.github.io/HFRGMTools/#avertissement-vie-priv%C3%A9e

ouais c'est bien ça, c'est clair (c'est ce qui devrait apparaitre dans une popup à la création du mp en plus du choix du multi destinataire :o )

bon en fait y'a confusion, je pensais que mpstorage était une bibliothèque générique utilisable par d'autres scripts, mais si elle est uniquement destiné à hfr4k, alors la note d’avertissement en question dans la doc d'hfr4k suffit bien

je voulais faire un autre ticket pour signaler les problèmes de généricité et de non isolation des données au sein de mpstorage :

le script client devrais dire à mp storage qu'elle nom de mp utiliser (et quel multi pour le destinataire) ainsi chaque script a son propre mp

et il ne devrait pas y avoir de gestion de structure ou de version des données dans mpstorage tous ces aspects doivent rester à la charge du script (bon là y'en a pas vraiment à part la structure par défaut qui n'a pas lieu d'être quoi)

mpstorage ne devrait juste gérer que la création/récupération/miseàjour du mp (en fonction de ce que lui donne le script pas avec des valeur globale)

mais donc je laisse

**Comment by Wiripse** [comment]
Pas un bug
