### ISSUE TITLE
plantage de la création du mp si l'utilisateur n'a aucun de mp

### ISSUE THREAD

**Issue by roger21** [Wiripse/HFRGMTools#29]
plantage à la ligne 207 de mpstorage si l'utilisateur n'a aucun de mp

`resp.getElementsByClassName('fondForum1PagesHaut')` n'existe pas

faire un test préalable sur l’existence de `resp.getElementsByClassName('fondForum1PagesHaut')`

et s'il n'existe pas définir maxpage à 1 (au lieu d'essayer de le recup)

et le reste devrait couler : pas de passage dans le boucle des mps puis passage dans le esle vers createStorageMP

c'est pas forcement compatible avec un plantage de la requête (pour n'importe qu'elle raison), dans ce cas `resp.getElementsByClassName('fondForum1PagesHaut')` pourrait ne pas exister non plus

**Comment by Wiripse** [comment]
Fixed by https://github.com/Wiripse/HFRGMTools/commit/e276244d7743ac4c351389676b19f0789a9c7b9d
